defmodule TheronsErp.Repo.Migrations.ReplenishmentImprovements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:replenishments) do
      modify :vendor_id, :uuid, null: false
      modify :product_id, :uuid, null: false
      modify :trigger_quantity, :decimal
      add :lead_time_days, :bigint
    end

    alter table(:movements) do
      modify :to_location_id, :uuid, null: false
      modify :from_location_id, :uuid, null: false
      modify :product_id, :uuid, null: false
    end
  end

  def down do
    alter table(:movements) do
      modify :product_id, :uuid, null: true
      modify :from_location_id, :uuid, null: true
      modify :to_location_id, :uuid, null: true
    end

    alter table(:replenishments) do
      remove :lead_time_days
      modify :trigger_quantity, :bigint
      modify :product_id, :uuid, null: true
      modify :vendor_id, :uuid, null: true
    end
  end
end
