defmodule TheronsErp.Repo.Migrations.AddMovements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:movements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :from_location, :text
      add :to_location, :text
      add :quantity, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actual_transfer_id,
          references(:ledger_transfers,
            column: :id,
            name: "movements_actual_transfer_id_fkey",
            type: :binary,
            prefix: "public"
          )

      add :predicted_transfer_id,
          references(:ledger_transfers,
            column: :id,
            name: "movements_predicted_transfer_id_fkey",
            type: :binary,
            prefix: "public"
          )

      add :eager_transfer_id,
          references(:ledger_transfers,
            column: :id,
            name: "movements_eager_transfer_id_fkey",
            type: :binary,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:movements, "movements_actual_transfer_id_fkey")

    drop constraint(:movements, "movements_predicted_transfer_id_fkey")

    drop constraint(:movements, "movements_eager_transfer_id_fkey")

    drop table(:movements)
  end
end
