defmodule TheronsErp.Repo.Migrations.AddDateToMovements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:replenishments) do
      modify :lead_time_days, :bigint, null: false, default: 1
    end

    alter table(:movements) do
      add :date, :date
    end
  end

  def down do
    alter table(:movements) do
      remove :date
    end

    alter table(:replenishments) do
      modify :lead_time_days, :bigint, null: true, default: nil
    end
  end
end
