defmodule TheronsErp.Repo.Migrations.ChangeLocationsFromStringsToRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:movements) do
      remove :to_location
      remove :from_location
      add :from_location_id, :uuid
      add :to_location_id, :uuid
    end

    create table(:locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:movements) do
      modify :from_location_id,
             references(:locations,
               column: :id,
               name: "movements_from_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :to_location_id,
             references(:locations,
               column: :id,
               name: "movements_to_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:locations) do
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:locations) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:movements, "movements_from_location_id_fkey")

    drop constraint(:movements, "movements_to_location_id_fkey")

    alter table(:movements) do
      modify :to_location_id, :uuid
      modify :from_location_id, :uuid
    end

    drop table(:locations)

    alter table(:movements) do
      remove :to_location_id
      remove :from_location_id
      add :from_location, :text
      add :to_location, :text
    end
  end
end
