defmodule TheronsErp.Repo.Migrations.CascadeDeleteLineItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:line_items, "line_items_invoice_id_fkey")

    alter table(:line_items) do
      modify :quantity, :bigint, null: false
      modify :price, :money_with_currency, null: false

      modify :invoice_id,
             references(:invoices,
               column: :id,
               name: "line_items_invoice_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:invoices) do
      modify :customer_id, :uuid, null: false
    end
  end

  def down do
    alter table(:invoices) do
      modify :customer_id, :uuid, null: true
    end

    drop constraint(:line_items, "line_items_invoice_id_fkey")

    alter table(:line_items) do
      modify :invoice_id,
             references(:invoices,
               column: :id,
               name: "line_items_invoice_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :price, :money_with_currency, null: true
      modify :quantity, :bigint, null: true
    end
  end
end
