defmodule TheronsErp.Repo.Migrations.MovePullLocationToSalesLines do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_orders) do
      remove :pull_location_id
    end

    alter table(:sales_lines) do
      add :pull_location_id,
          references(:locations,
            column: :id,
            name: "sales_lines_pull_location_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:sales_lines, "sales_lines_pull_location_id_fkey")

    alter table(:sales_lines) do
      remove :pull_location_id
    end

    alter table(:sales_orders) do
      add :pull_location_id,
          references(:locations,
            column: :id,
            name: "sales_orders_pull_location_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
