defmodule TheronsErp.Repo.Migrations.AddLineItemsToInvoices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_lines) do
      modify :quantity, :bigint, default: 1
    end

    create table(:line_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :price, :money_with_currency
      add :quantity, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :invoice_id, :uuid
    end

    create table(:invoices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:line_items) do
      modify :invoice_id,
             references(:invoices,
               column: :id,
               name: "line_items_invoice_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:invoices) do
      add :identifier, :bigserial

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:entities,
            column: :id,
            name: "invoices_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :state, :text, null: false, default: "draft"
    end
  end

  def down do
    drop constraint(:invoices, "invoices_customer_id_fkey")

    alter table(:invoices) do
      remove :state
      remove :customer_id
      remove :updated_at
      remove :inserted_at
      remove :identifier
    end

    drop constraint(:line_items, "line_items_invoice_id_fkey")

    alter table(:line_items) do
      modify :invoice_id, :uuid
    end

    drop table(:invoices)

    drop table(:line_items)

    alter table(:sales_lines) do
      modify :quantity, :bigint, default: nil
    end
  end
end
