defmodule TheronsErp.Repo.Migrations.Routes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:routes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :fallback, :text
      add :routes, {:array, :map}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:purchase_order_items) do
      add :state, :text, null: false, default: "draft"
    end

    alter table(:products) do
      add :route_id,
          references(:routes,
            column: :id,
            name: "products_route_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:products, "products_route_id_fkey")

    alter table(:products) do
      remove :route_id
    end

    alter table(:purchase_order_items) do
      remove :state
    end

    drop table(:routes)
  end
end
