defmodule TheronsErp.Repo.Migrations.AddPaidAmountToInvoices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:invoices) do
      add :paid_amount, :money_with_currency
    end
  end

  def down do
    alter table(:invoices) do
      remove :paid_amount
    end
  end
end
