defmodule TheronsErp.Repo.Migrations.AddSaleableAndPurchaseableToProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :saleable, :boolean, default: true
      add :purchaseable, :boolean, default: false
    end
  end

  def down do
    alter table(:products) do
      remove :purchaseable
      remove :saleable
    end
  end
end
