defmodule TheronsErp.Repo.Migrations.DestLocationForPos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:purchase_orders) do
      add :destination_location_id,
          references(:locations,
            column: :id,
            name: "purchase_orders_destination_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :state, :text, null: false, default: "created"
    end
  end

  def down do
    drop constraint(:purchase_orders, "purchase_orders_destination_location_id_fkey")

    alter table(:purchase_orders) do
      remove :state
      remove :destination_location_id
    end
  end
end
