defmodule TheronsErp.Repo.Migrations.AddArchivalToProductCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:product_categories) do
      modify :full_name, :text, null: false
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:product_categories) do
      remove :archived_at
      modify :full_name, :text, null: true
    end
  end
end
