defmodule TheronsErp.Repo.Migrations.AddAddress2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:addresses) do
      add :address2, :text
    end
  end

  def down do
    alter table(:addresses) do
      remove :address2
    end
  end
end
