defmodule TheronsErp.Repo.Migrations.AddCostToProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :cost, :money_with_currency
    end
  end

  def down do
    alter table(:products) do
      remove :cost
    end
  end
end
