defmodule TheronsErp.Repo.Migrations.AddPurchaseOrderToMovements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:movements) do
      add :purchase_order_id,
          references(:purchase_orders,
            column: :id,
            name: "movements_purchase_order_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:movements, "movements_purchase_order_id_fkey")

    alter table(:movements) do
      remove :purchase_order_id
    end
  end
end
