defmodule TheronsErp.Repo.Migrations.AddPeopleToSalesOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_orders) do
      add :customer_id,
          references(:entities,
            column: :id,
            name: "sales_orders_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:sales_orders, "sales_orders_customer_id_fkey")

    alter table(:sales_orders) do
      remove :customer_id
    end
  end
end
