defmodule TheronsErp.Repo.Migrations.PurchaseOrderItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:purchase_order_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal
      add :unit_price, :money_with_currency

      add :purchase_order_id,
          references(:purchase_orders,
            column: :id,
            name: "purchase_order_items_purchase_order_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :product_id,
          references(:products,
            column: :id,
            name: "purchase_order_items_product_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:purchase_order_items, "purchase_order_items_purchase_order_id_fkey")

    drop constraint(:purchase_order_items, "purchase_order_items_product_id_fkey")

    drop table(:purchase_order_items)
  end
end
