defmodule TheronsErp.Repo.Migrations.AddReplenishmentToPurchaseOrderLine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:purchase_order_items) do
      add :replenishment_id,
          references(:replenishments,
            column: :id,
            name: "purchase_order_items_replenishment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:purchase_order_items, "purchase_order_items_replenishment_id_fkey")

    alter table(:purchase_order_items) do
      remove :replenishment_id
    end
  end
end
