defmodule TheronsErp.Repo.Migrations.AddSalesOrderToInvoice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:invoices) do
      add :sales_order_id,
          references(:sales_orders,
            column: :id,
            name: "invoices_sales_order_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:invoices, "invoices_sales_order_id_fkey")

    alter table(:invoices) do
      remove :sales_order_id
    end
  end
end
