defmodule TheronsErp.Repo.Migrations.AddTriggerQuantityToReplenishment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:replenishments) do
      add :trigger_quantity, :bigint
    end
  end

  def down do
    alter table(:replenishments) do
      remove :trigger_quantity
    end
  end
end
