defmodule TheronsErp.Repo.Migrations.AddProcessDateToSalesOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_orders) do
      add :process_date, :date
    end
  end

  def down do
    alter table(:sales_orders) do
      remove :process_date
    end
  end
end
