defmodule TheronsErp.Repo.Migrations.AddProductToLineItem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:line_items) do
      modify :invoice_id, :uuid, null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "line_items_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:line_items, "line_items_product_id_fkey")

    alter table(:line_items) do
      remove :product_id
      modify :invoice_id, :uuid, null: true
    end
  end
end
