defmodule TheronsErp.Repo.Migrations.AddProductToMovements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:movements) do
      add :manually_created, :boolean, default: false

      add :product_id,
          references(:products,
            column: :id,
            name: "movements_product_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:movements, "movements_product_id_fkey")

    alter table(:movements) do
      remove :product_id
      remove :manually_created
    end
  end
end
