defmodule TheronsErp.Repo.Migrations.ManyToManyRoutes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      remove :route_id
    end

    create table(:product_routes, primary_key: false) do
      add :product_id,
          references(:products,
            column: :id,
            name: "product_routes_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :routes_id,
          references(:routes,
            column: :id,
            name: "product_routes_routes_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:product_routes, "product_routes_product_id_fkey")

    drop constraint(:product_routes, "product_routes_routes_id_fkey")

    drop table(:product_routes)

    alter table(:products) do
      add :route_id,
          references(:routes,
            column: :id,
            name: "products_route_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
