defmodule TheronsErp.Repo.Migrations.GeneratePurchaseOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vendors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :address, :text
      add :phone, :text
      add :email, :text
      add :city, :text
      add :state, :text
      add :zip_coe, :text
      add :identifier, :bigserial

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:purchase_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :order_date, :date
      add :delivery_date, :date
      add :total_amount, :money_with_currency

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vendor_id,
          references(:vendors,
            column: :id,
            name: "purchase_orders_vendor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:purchase_orders, "purchase_orders_vendor_id_fkey")

    drop table(:purchase_orders)

    drop table(:vendors)
  end
end
