defmodule TheronsErp.Repo.Migrations.UniqueLocationName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_orders) do
      add :pull_location_id,
          references(:locations,
            column: :id,
            name: "sales_orders_pull_location_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:locations, [:name], name: "locations_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:locations, [:name], name: "locations_unique_name_index")

    drop constraint(:sales_orders, "sales_orders_pull_location_id_fkey")

    alter table(:sales_orders) do
      remove :pull_location_id
    end
  end
end
